### ISSUE TITLE
provide a ranking for mutual funds

### ISSUE THREAD

**Issue by wiki-me** [Econiverse/econiverse#4]
something like morningstar star rating, maybe using a simple [sharpe ratio](https://www.investopedia.com/terms/s/sharperatio.asp),   or maybe more advanced that is possibly a more reliable indicator such as [this](https://www.researchgate.net/publication/275892875_Mutual_Fund_Performance_Luck_or_Skill).

**Comment by lunarnautics** [comment]
I haven't forgotten about this, but I want to put it on the back burner for now
