### ISSUE TITLE
Love this project! Increase in visibility

### ISSUE THREAD

**Issue by DidierRLopes** [Econiverse/econiverse#8]
For people that come across this project, the link may seem a bit hidden. 

Could you add it in the link of the repo, so that it appears straight on the top right. Here
<img width="281" alt="Screen Shot 2021-09-25 at 00 55 11" src="https://user-images.githubusercontent.com/25267873/134750391-0061aa9d-6400-4cb9-961b-a49cd7a4ef46.png">

**Comment by lunarnautics** [comment]
Great suggestion! Just updated it now
